//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamShelterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalPicture
    {
        public int id { get; set; }
        public int animalId { get; set; }
        public string imageUrl { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
