//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamShelterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.ApplicationForAnimals = new HashSet<ApplicationForAnimal>();
            this.AnimalPictures = new HashSet<AnimalPicture>();
        }
    
        public int id { get; set; }
        public int workerId { get; set; }
        public string animalType { get; set; }
        public string name { get; set; }
        public string breed { get; set; }
        public string gender { get; set; }
        public System.DateTime birthDate { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> animalWeight { get; set; }
        public Nullable<System.DateTime> vacinationDate { get; set; }
        public Nullable<System.DateTime> dewormingDate { get; set; }
        public bool hasMicrochip { get; set; }
        public bool readyForAdoption { get; set; }
        public string comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForAnimal> ApplicationForAnimals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalPicture> AnimalPictures { get; set; }
        public virtual Person Person { get; set; }
    }
}
