//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamShelterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Animals = new HashSet<Animal>();
            this.ApplicationForAnimals = new HashSet<ApplicationForAnimal>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public string streetAddress { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int personRole { get; set; }
        public int shelterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForAnimal> ApplicationForAnimals { get; set; }
        public virtual Shelter Shelter { get; set; }
    }
}
