//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamShelterProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShelterProjectEntities : DbContext
    {
        public ShelterProjectEntities()
            : base("name=ShelterProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<AnimalPicture> AnimalPictures { get; set; }
        public virtual DbSet<ApplicationForAnimal> ApplicationForAnimals { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Shelter> Shelters { get; set; }

        public System.Data.Entity.DbSet<TeamShelterProject.Models.ShelterMD> ShelterMDs { get; set; }
    }
}
